In [1]:
import numpy as np
import pandas as pd

In [3]:
filePath = '../dataset/d50_4/synthetic_data_expt1.csv'
df = pd.read_csv(filePath)
col_list = df.columns
print (col_list)
print ("Total columns:",  len(col_list))

Index(['0', '1', '2', '3'], dtype='object')
Total columns: 4


In [5]:
print("Saving the cleaned data frames to csv files")
fy_csv_file = '../dataset/d50_4/test1-fy.csv'
sy_csv_file = '../dataset/d50_4/test1-sy.csv'
merge_csv_file = '../dataset/d50_4/test1-merge.csv'

df_fy.to_csv(fy_csv_file, encoding='utf-8', index=False)
df_sy.to_csv(sy_csv_file, encoding='utf-8', index=False)
df_merge.to_csv(merge_csv_file, encoding='utf-8', index=False)

Saving the cleaned data frames to csv files


NameError: name 'df_fy' is not defined

In [10]:
def load_disease_data_perturb(filePath, prob):
    """ Creates a numpy array from given csv file

    Creates a pandas dataframe from the given csv file and then exports it to 
    a numpy ndarray. Also perfoms the check where any value > 0 is mapped to 1 
    since it corresponds to a particular disease being prevalent.

    Args:
        filePath: Path to the csv file to load the disease data from
        prob: perturbation probability for 0 to 1

    Returns:
        A binary (0-1) numpy ndarray with each row corresponding to a particular 
        person's disease prevalence data. 
    """
    df = pd.read_csv(filePath)
    tups = [tuple(x) for x in df.values]
    data_arr = np.asarray(tups)
    print(data_arr[:10])
    # Map all positive values to 1 since any > 0 indicates the disease
    data_arr[data_arr > 0] = 1
    
    p_mat = np.random.random(size=data_arr.shape)
    p_idx = (p_mat <= prob)
    data_arr[p_idx] = 1 # If there was 1 prev, no problem, but if there was a 0, map it to 1    
    
    return data_arr

a = load_disease_data_perturb('../dataset/d50_4/synthetic_data_expt1.csv', 0.6)
print(a[:10])

[[0 0 0 0]
 [1 1 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]
 [0 0 0 0]]
[[0 0 1 1]
 [1 1 0 1]
 [0 1 0 1]
 [1 0 1 1]
 [1 1 0 1]
 [0 1 0 0]
 [0 0 0 0]
 [1 1 1 0]
 [1 1 1 0]
 [1 1 0 1]]


In [28]:
x = np.random.randint(2, size=(34,15))
p_matrix = np.random.random(size=x.shape)

In [29]:
prob = 0.4
p_idx= (p_matrix <= prob)
x[p_idx] = 1    # If there was 1 prev, no problem, but if there was a zero, map it to 1




In [ ]:
# Loading the toy-dataset
filePath = '../data/Age50_DataExtract.csv'
df = pd.read_csv(filePath)

In [ ]:
print df.columns

In [ ]:
drop_list = ['fyAGE', 'CCCfy98.1']
df = df.drop(drop_list, axis=1)

In [ ]:
col_list = df.columns

In [ ]:
fy_list = col_list[:9]
sy_list = col_list[9:]

df_fy = df.filter(fy_list, axis=1)
df_sy = df.filter(sy_list, axis=1)


In [ ]:
print "Saving the clean csv files"

fname_merge = '../data/Age50_DataExtract_merge.csv'
fname_fy = '../data/Age50_DataExtract_fy.csv'
fname_sy = '../data/Age50_DataExtract_sy.csv'

df.to_csv(fname_merge, encoding='utf-8', index=False)
df_fy.to_csv(fname_fy, encoding='utf-8', index=False)
df_sy.to_csv(fname_sy, encoding='utf-8', index=False)

In [ ]:
tups = [tuple(x) for x in df.values]
data_arr = np.asarray(tups)

In [ ]:
data_arr

In [ ]:
data_arr.shape

In [ ]:
# Make multi valued discrete data into binary


# converts column j to binary vec
def convert_discrete_data(data, j):
    # set of values
    valset = set(data[:,j])
    valdict = {}
    count = 0
    for i in valset:
        valdict[i] = count
        count += 1
    
    m = len(valset)
    
    # Now remap the data set
    
    N = data.shape[0]
    
    ndata = np.zeros((N,m))
    
    for i in range(N):
        pos = valdict[data[i,j]]
        ndata[i,pos] = 1 #one hot encoding
    
    new_arr = np.concatenate((data[:,:j], ndata, data[:,j+1:]), axis=1)
    return new_arr
                            


nd = convert_discrete_data(data_arr,20)



In [ ]:
data_arr[:5]

In [ ]:
nd[:5]